# fly.toml app configuration file generated for ff-bot on 2023-09-13T15:05:57-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ff-bot"
primary_region = "dfw"

[build]

[processes]
  worker = "python main.py"
